FROM jenkins/jenkins:lts

USER root

RUN apt-get update -q && \
    apt-get install -y python3 python3-pip python3-venv docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
